In [2]:
#Write a Python function which will sum all the following listed items (5,8,2,4,7,9)
def add(a,b,c,d,e,f):
    return a+b+c+d+e+f
add(5,8,2,4,7,9)

35

In [5]:
#Write a Python function whihc will find the product/multiply the items in the following list: (4,3,5,6,2)
def multiply(a,b,c,d,e):
    return a*b*c*d*e
multiply(4,3,5,6,2)

720

In [7]:

import numpy as np

In [8]:
# Creating arrays from a list with float16 data type
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]], dtype='float16')
print(array_hw)

[[5. 5. 8. 8. 9. 8.]
 [7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]


In [13]:
#Sort the flattened array
print ('array_hw:')
print (array_hw)
print('')
print('array_hw Simple Sort:')
np.sort(array_hw, axis=None)

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

array_hw Simple Sort:


array([1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
       9, 9])

In [16]:
## Sort the second column:
print ('array_hw:')
print (array_hw)
print('')
print('array_hw Simple Sort:')
np.sort(array_hw, axis=0)

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

array_hw Simple Sort:


array([[5, 5, 5, 3, 1, 4],
       [7, 7, 7, 3, 2, 6],
       [8, 7, 8, 4, 5, 7],
       [9, 9, 8, 8, 9, 8]])

In [18]:
## Sort the third row:
print ('array_hw:')
print (array_hw)
print('')
print('array_hw Simple Sort:')
np.sort(array_hw, axis=1)

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

array_hw Simple Sort:


array([[5, 5, 8, 8, 8, 9],
       [3, 5, 5, 7, 7, 7],
       [2, 4, 6, 7, 8, 8],
       [1, 3, 4, 7, 9, 9]])

In [15]:
#Extract the second row onwards
print ('array_hw:')
print (array_hw[1:,...])

array_hw:
[[7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]


In [26]:
#obtain the square root of array_hw
np.sqrt(array_hw)

array([[2.23606798, 2.23606798, 2.82842712, 2.82842712, 3.        ,
        2.82842712],
       [2.64575131, 2.64575131, 2.23606798, 1.73205081, 2.23606798,
        2.64575131],
       [2.82842712, 2.64575131, 2.82842712, 2.        , 1.41421356,
        2.44948974],
       [3.        , 3.        , 2.64575131, 1.73205081, 1.        ,
        2.        ]])

In [22]:
#obtain the square  of array_hw
print(array_hw)
print ('square  of array_hw')
np.square(array_hw)

[[5. 5. 8. 8. 9. 8.]
 [7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]
square  of array_hw


array([[25., 25., 64., 64., 81., 64.],
       [49., 49., 25.,  9., 25., 49.],
       [64., 49., 64., 16.,  4., 36.],
       [81., 81., 49.,  9.,  1., 16.]], dtype=float16)

In [34]:
#Slice the element from the third row and fourth column position 3X4
print(array_hw)
print ('element from the third row and fourth column position 3X4')
print(array_hw[2:,3:])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
[[4 2 6]
 [3 1 4]]


In [36]:
#obtain the total sum of array_hw
print(array_hw)
np.sum(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


145

In [40]:
#How many dimentions does array_hw have?
print(array_hw)
np.shape(array_hw)


[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


(4, 6)

In [21]:
#How many dimentions does array_hw have?
print(array_hw)
print ('dimentions in  array_hw is')
np.size(array_hw)


[[5. 5. 8. 8. 9. 8.]
 [7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]
dimentions in  array_hw is


24

In [20]:
#What is the data type listed in array_hw
print(array_hw)
print ( 'data type listed in array_hw is')
a=np.array(array_hw)
a.dtype 

[[5. 5. 8. 8. 9. 8.]
 [7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]
data type listed in array_hw is


dtype('float16')

In [19]:
#What is the data type listed in array_hw
print(array_hw)
print ('data type listed in array_hw')
a=np.array(array_hw)
a.nbytes 


[[5. 5. 8. 8. 9. 8.]
 [7. 7. 5. 3. 5. 7.]
 [8. 7. 8. 4. 2. 6.]
 [9. 9. 7. 3. 1. 4.]]
data type listed in array_hw


48

In [18]:
# Extract the third column onwards
print ('array_hw Extract the third column onwards')
print (array_hw[...,2:])

array_hw Extract the third column onwards
[[8. 8. 9. 8.]
 [5. 3. 5. 7.]
 [8. 4. 2. 6.]
 [7. 3. 1. 4.]]
